# Generated by Django 4.2.6 on 2023-11-19 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=320, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('cep', models.CharField(max_length=14)),
                ('neighborhood', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=20)),
                ('complement', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('id_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('user_url', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=14)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.account')),
                ('adress', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.adress')),
                ('category', models.ManyToManyField(to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='EstablishmentDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_day', to='home.day')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establishment_day', to='home.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('establishment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='home.establishment')),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialInterval', models.TimeField(max_length=5)),
                ('closeInterval', models.TimeField(max_length=5)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='home.establishmentday')),
            ],
        ),
        migrations.AddField(
            model_name='establishment',
            name='days',
            field=models.ManyToManyField(related_name='establishment', through='home.EstablishmentDay', to='home.day'),
        ),
    ]
