# Generated by Django 4.2.6 on 2023-11-20 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interval',
            old_name='closeInterval',
            new_name='close_Interval',
        ),
        migrations.RenameField(
            model_name='interval',
            old_name='initialInterval',
            new_name='initial_nterval',
        ),
    ]
