# Generated by Django 4.2.6 on 2023-11-13 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initialInterval', models.TimeField(max_length=5)),
                ('closeInterval', models.TimeField(max_length=5)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.day')),
            ],
        ),
    ]
