# Generated by Django 4.2.6 on 2023-11-25 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_rename_close_interval_interval_close_interval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='account',
        ),
        migrations.AddField(
            model_name='establishment',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
