# Generated by Django 4.2.6 on 2023-11-25 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_remove_establishment_user_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establishment',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='establishment', to=settings.AUTH_USER_MODEL),
        ),
    ]
