# Generated by Django 4.2.6 on 2023-11-26 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_establishment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='day',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='interval',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervals', to='home.establishmentday'),
        ),
    ]
